### ISSUE TITLE
2.82 Not working！

### ISSUE THREAD

**Issue by hahajaja** [TitusLVR/InteractionOps#8]
![20200324005541](https://user-images.githubusercontent.com/23209894/77341825-459b7b80-6d6a-11ea-9e33-04c2b89549b7.png)
![20200324005534](https://user-images.githubusercontent.com/23209894/77341826-459b7b80-6d6a-11ea-9ac4-b645987a8577.png)

**Comment by Furash** [comment]
You have to rename the addon folder to **InteractionOps**. Right now you have **InteractionOps-master**

**Comment by hahajaja** [comment]
thank you
